import "./globals.css";
import { Signika } from "next/font/google";

const signika = Signika({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt_BR">
            <head>
                <meta name="application-name" content="Lifit" />
                <meta name="apple-mobile-web-app-capable" content="yes" />
                <meta
                    name="apple-mobile-web-app-status-bar-style"
                    content="default"
                />
                <meta name="apple-mobile-web-app-title" content="Lifit" />
                <meta name="description" content="Sua vida mais saudável" />
                <meta name="format-detection" content="telephone=no" />
                <meta name="mobile-web-app-capable" content="yes" />
                <meta
                    name="msapplication-config"
                    content="/icons/browserconfig.xml"
                />
                <meta name="msapplication-TileColor" content="#E5FDDF" />
                <meta name="msapplication-tap-highlight" content="no" />
                <meta name="theme-color" content="#E5FDDF" />

                <link
                    rel="apple-touch-icon"
                    href="/images/icons/lifit-192-192.png"
                />
                <link
                    rel="apple-touch-icon"
                    sizes="152x152"
                    href="/images/icons/lifit-192-192.png"
                />
                <link
                    rel="apple-touch-icon"
                    sizes="180x180"
                    href="/images/icons/lifit-192-192.png"
                />
                <link
                    rel="apple-touch-icon"
                    sizes="167x167"
                    href="/images/icons/lifit-192-192.png"
                />

                <link
                    rel="icon"
                    type="image/png"
                    sizes="32x32"
                    href="/images/icons/lifit-192-192.png"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="16x16"
                    href="/images/icons/lifit-192-192.png"
                />
                <link rel="manifest" href="/manifest.json" />
                <link
                    rel="mask-icon"
                    href="/images/icons/lifit-192-192.png"
                    color="#E5FDDF"
                />
                <link
                    rel="shortcut icon"
                    href="/images/icons/lifit-192-192.png"
                />

                <meta name="twitter:card" content="summary" />
                <meta name="twitter:url" content="https://lifit.app" />
                <meta name="twitter:title" content="Lifit" />
                <meta
                    name="twitter:description"
                    content="Sua vida mais saudável"
                />
                <meta
                    name="twitter:image"
                    content="https://lifit.app/images/icons/lifit-512-512.png"
                />
                <meta name="twitter:creator" content="@lifit" />
                <meta property="og:type" content="website" />
                <meta property="og:title" content="Lifit" />
                <meta
                    property="og:description"
                    content="Sua vida mais saudável"
                />
                <meta property="og:site_name" content="Lifit" />
                <meta property="og:url" content="https://lifit.app" />
                <meta
                    property="og:image"
                    content="https://lifit.app/images/icons/lifit-512-512.png"
                />

                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_2048.png"
                    sizes="2048x2732"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_1668.png"
                    sizes="1668x2224"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_1536.png"
                    sizes="1536x2048"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_1125.png"
                    sizes="1125x2436"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_1242.png"
                    sizes="1242x2208"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_750.png"
                    sizes="750x1334"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/images/apple/apple_splash_640.png"
                    sizes="640x1136"
                />
            </head>
            <body className={`${signika.className}`}>{children}</body>
        </html>
    );
}
