import "./globals.css";
import { Signika } from "next/font/google";

const signika = Signika({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt_BR">
            <body
                className={`${signika.className} bg-bg-default text-text-default`}
            >
                {children}
            </body>
        </html>
    );
}
